---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gitlab
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: GitLab
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}