---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: sonarqube
      version: 6.0.0+403
      sourceRef:
        kind: HelmRepository
        name: SonarSource
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}