
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: SonarSource
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: ${helmMirrorURL:=https://SonarSource.github.io/helm-chart-sonarqube}
  interval: 5m