---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gitlab-runner
      version: 0.46.0
      sourceRef:
        kind: HelmRepository
        name: GitLab
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}